### ISSUE TITLE
Is it still working?

### ISSUE THREAD

**Issue by matthieuEv** [Sylicium/zone-telechargement-api#2]
Hi, just wanted to ask if it was still on?

**Comment by Sylicium** [comment]
Hey !
Unfortunately, a friend warned me about the legality of this API and I had to close it some time after opening it to prevent any problems.

Howerver if you can code in Javascript (NodeJS) just take a look at the `/localModules/ztParser.js` file, its the core of the project and API, and only this file is really important. (All other files are needed to make an API around that file in fact)
You can import it to your project to use it by your own.

I will edit the repository to talk about that.

**Comment by Sylicium** [comment]
I updated README.md file, go take a look ^^

**Comment by matthieuEv** [comment]
Huge Thanks, ill look on it 😁
